apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: timestamp-authority
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: timestamp-authority
    app.kubernetes.io/part-of: timestamp-authority
  name: timestamp-authorityo5vb
spec:
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: timestamp-authority
    weight: 100
status: {}
